name: customer-insights-env

channels:
  - defaults

dependencies:
  - python=3.11

  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - openpyxl

  - pip

  - pip:
      - notebook